positions:
  - DEV
  - MOB
  - QA
  - IT
  - WC
  - IE
  - DESIGN
  - ADMIN

users:
  - name: Andres
    last_name: Hernandez Monge
    email: ahernandez@growthaccelerationpartners.com
    employee_type: Regular
    location: Site 1
    roles:
      - admin
      - personnel_manager
  - name: Roy
    last_name: Rivera Zamora
    email: rrivera@growthaccelerationpartners.com
    employee_type: Regular
    location: Site 1
    roles:
      - admin
  - name: Sergio
    last_name: Monge Vargas
    email: svargas@growthaccelerationpartners.com
    employee_type: Regular
    location: Site 1
    roles:
      - admin
      - personnel_manager

practices:
  - name: Rails
    description:
    icon: diamond
  - name: Android
    description:
    icon: android
  - name: iOS
    description:
    icon: apple
  - name: Java
    description:
    icon: coffee
  - name: Python
    description:
    icon: language-python
  - name: Coaching
    description:
    icon: account-multiple
  - name: Agile
    description:
    icon: chart-timeline
  - name: Javascript
    description:
    icon: language-javascript
  - name: Architecture
    description:
    icon: amazon-clouddrive
  - name: .Net
    description:
    icon: language-csharp
  - name: QA Manual
    description:
    icon: bug
  - name: QA Automation
    description:
    icon: laptop
  - name: QA Mobile
    description:
    icon: cellphone

videos:
  - name: 'ROR Workshop: 18 - Refactoring Code'
    url: 'https://www.youtube.com/watch?v=0iImjqzEBkk'
    tags: 'refactoring, ruby'
    description: 'Video description'
  - name: 'ROR Workshop: SSO-Devise and OmniAuth'
    url: 'https://www.youtube.com/watch?v=uYFkSsmuZuw'
    tags: 'sso, devise, omniauth'
    description: 'Video description'
  - name: 'RoR Worshop 12: Active Record When yes and no'
    url: 'https://www.youtube.com/watch?v=dc9ytssus0k'
    tags: 'active, record, rails'
    description: 'Video description'
  - name: 'ROR Workshop: 16 - Build Gems'
    url: 'https://www.youtube.com/watch?v=Rm8Jp7VqZTU'
    tags: 'build, gems, engines'
    description: 'Video description'
  - name: 'RoR Worshop 13: RVM: Ruby Virtual Machine'
    url: 'https://www.youtube.com/watch?v=MF2U3K25qdQ'
    tags: 'rvm'
    description: 'Video description'
  - name: 'RoR Workshop 11: SOLID (object oriented design)'
    url: 'https://www.youtube.com/watch?v=LZHLH7cWAmM'
    tags: 'solid, object, oriented, design'
    description: 'Video description'
  - name: 'RoR Workshop 1: Static Code Analizers in Rails'
    url: 'https://www.youtube.com/watch?v=QyoexmPxBGw'
    tags: 'static, code, analizers'
    description: 'Video description'
  - name: 'A Test Video'
    url: 'https://www.youtube.com/watch?v=u3mw8IaWFSQ'
    tags: 'drg, test, rails'
    description: 'Video description'
