positions:
  - DEV
  - MOB
  - QA
  - IT
  - WC
  - IE
  - DESIGN
  - ADMIN

users:
  - name: Andres
    last_name: Hernandez Monge
    email: ahernandez@growthaccelerationpartners.com
    employee_type: Regular
    location: Site 1
    roles:
      - admin
      - personnel_manager
  - name: Roy
    last_name: Rivera Zamora
    email: rrivera@growthaccelerationpartners.com
    employee_type: Regular
    location: Site 1
    roles:
      - admin
  - name: Sergio
    last_name: Monge Vargas
    email: svargas@growthaccelerationpartners.com
    employee_type: Regular
    location: Site 1
    roles:
      - admin
      - personnel_manager

practices:
  - name: Rails
    description:
    icon: bulletin-board
  - name: Android
    description:
    icon: android
  - name: iOS
    description:
    icon: apple
  - name: Java
    description:
    icon: coffee
  - name: Python
    description:
    icon: language-python
  - name: Coaching
    description:
    icon: account-multiple
  - name: Agile
    description:
    icon: chart-timeline
  - name: Javascript
    description:
    icon: language-javascript
  - name: Architecture
    description:
    icon: amazon-clouddrive
  - name: .Net
    description:
    icon: language-csharp
  - name: QA Manual
    description:
    icon: bug
  - name: QA Automation
    description:
    icon: laptop
  - name: QA Mobile
    description:
    icon: cellphone
