development:
  GOOGLE_CLIENT_ID: 'CLIENT_ID'
  GOOGLE_CLIENT_SECRET: 'CLIENT_SECRET'
test:
  GOOGLE_CLIENT_ID: 'CLIENT_ID'
  GOOGLE_CLIENT_SECRET: 'CLIENT_SECRET'
production:
  GOOGLE_CLIENT_ID: 'CLIENT_ID'
  GOOGLE_CLIENT_SECRET: 'CLIENT_SECRET'
